const PEOPLE = 6;
const STORAGE_KEY = 'viajecillos-v1-expenses';

const trip = [
  {date:'2026-09-06',place:'Huaraz — K67',gross:{transport:720,hotel:420,food:600,mobility:108},net:{transport:590.40,hotel:344.40,food:492,mobility:88.56},target:{transport:382.50,hotel:160,food:100.02,mobility:44.28}},
  {date:'2026-09-07',place:'Traslado Huaraz → Chimbote',gross:{transport:0,hotel:0,food:0,mobility:0},net:{transport:0,hotel:0,food:0,mobility:0},target:{transport:0,hotel:0,food:0,mobility:0}},
  {date:'2026-09-08',place:'MegaPlaza Chimbote — B50',gross:{transport:480,hotel:840,food:300,mobility:108},net:{transport:393.60,hotel:688.80,food:246,mobility:88.56},target:{transport:300,hotel:150,food:94.98,mobility:44.28}},
  {date:'2026-09-09',place:'Chimbote — K46',gross:{transport:0,hotel:420,food:300,mobility:108},net:{transport:0,hotel:344.40,food:246,mobility:88.56},target:{transport:0,hotel:150,food:94.98,mobility:44.28}},
  {date:'2026-09-10',place:'Metro Balta Chiclayo — B77',gross:{transport:480,hotel:420,food:300,mobility:108},net:{transport:393.60,hotel:344.40,food:246,mobility:88.56},target:{transport:262.50,hotel:160,food:100.02,mobility:44.28}},
  {date:'2026-09-11',place:'Real Plaza Chiclayo — K24',gross:{transport:0,hotel:420,food:300,mobility:108},net:{transport:0,hotel:344.40,food:246,mobility:88.56},target:{transport:0,hotel:160,food:100.02,mobility:44.28}},
  {date:'2026-09-12',place:'Mall Aventura Chiclayo — T81',gross:{transport:0,hotel:420,food:300,mobility:108},net:{transport:0,hotel:344.40,food:246,mobility:88.56},target:{transport:0,hotel:160,food:100.02,mobility:44.28}},
  {date:'2026-09-13',place:'Open Plaza Piura II — T72',gross:{transport:480,hotel:420,food:300,mobility:108},net:{transport:393.60,hotel:344.40,food:246,mobility:88.56},target:{transport:169.50,hotel:0,food:94.98,mobility:44.28}},
  {date:'2026-09-14',place:'Real Plaza Piura — B25',gross:{transport:0,hotel:420,food:300,mobility:108},net:{transport:0,hotel:344.40,food:246,mobility:88.56},target:{transport:0,hotel:150,food:94.98,mobility:44.28}},
  {date:'2026-09-15',place:'Plaza del Sol Piura — K21',gross:{transport:0,hotel:420,food:300,mobility:108},net:{transport:0,hotel:344.40,food:246,mobility:88.56},target:{transport:0,hotel:150,food:94.98,mobility:44.28}},
  {date:'2026-09-16',place:'Plaza de la Luna — T96',gross:{transport:0,hotel:420,food:300,mobility:108},net:{transport:0,hotel:344.40,food:246,mobility:88.56},target:{transport:0,hotel:150,food:94.98,mobility:44.28}},
  {date:'2026-09-17',place:'Sullana — K53',gross:{transport:480,hotel:420,food:300,mobility:108},net:{transport:393.60,hotel:344.40,food:246,mobility:88.56},target:{transport:71.25,hotel:140,food:94.98,mobility:44.28}},
  {date:'2026-09-18',place:'Costamar Plaza Tumbes — T40',gross:{transport:480,hotel:420,food:300,mobility:108},net:{transport:393.60,hotel:344.40,food:246,mobility:88.56},target:{transport:482.40,hotel:180,food:105,mobility:44.28}},
  {date:'2026-09-19',place:'Av. Bolívar, Tumbes — H33',gross:{transport:1290,hotel:840,food:600,mobility:108},net:{transport:1057.80,hotel:688.80,food:492,mobility:88.56},target:{transport:0,hotel:180,food:105,mobility:44.28}},
  {date:'2026-09-20',place:'Retorno Tumbes → Lima',gross:{transport:0,hotel:0,food:0,mobility:0},net:{transport:0,hotel:0,food:0,mobility:0},target:{transport:0,hotel:0,food:0,mobility:0}}
];
const keys=['transport','hotel','food','mobility'];const money=n=>new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN',minimumFractionDigits:2}).format(Number.isFinite(n)?n:0);const sumObj=obj=>keys.reduce((s,k)=>s+(Number(obj[k])||0),0);const sumTrip=field=>trip.reduce((s,d)=>s+sumObj(d[field]),0);const formatDate=iso=>new Intl.DateTimeFormat('es-PE',{day:'2-digit',month:'short',timeZone:'UTC'}).format(new Date(`${iso}T00:00:00Z`));let saved=load();let currentIndex=firstPendingIndex();const $=id=>document.getElementById(id);const els={daySelect:$('daySelect'),dayMeta:$('dayMeta'),form:$('expenseForm'),saveMessage:$('saveMessage'),table:$('tripTableBody'),cards:$('tripCards'),saveProgress:$('saveProgressBtn'),closeDay:$('closeDayBtn'),reopenDay:$('reopenDayBtn'),inputs:{transport:$('transportInput'),hotel:$('hotelInput'),food:$('foodInput'),mobility:$('mobilityInput')},hints:{transport:$('transportHint'),hotel:$('hotelHint'),food:$('foodHint'),mobility:$('mobilityHint')}};
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return {}}}function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(saved))}function firstPendingIndex(){const i=trip.findIndex(d=>!saved[d.date]?.closed);return i>=0?i:trip.length-1}function actualFor(day){return saved[day.date]?.actual||{transport:0,hotel:0,food:0,mobility:0}}function hasProgress(day){return Boolean(saved[day.date]?.actual)}function isClosed(day){return Boolean(saved[day.date]?.closed)}function plannedSavings(day){return sumObj(day.net)-sumObj(day.target)}function actualSavings(day){return sumObj(day.net)-sumObj(actualFor(day))}function projectedSpendFor(day){if(isClosed(day))return sumObj(actualFor(day));if(hasProgress(day))return Math.max(sumObj(day.target),sumObj(actualFor(day)));return sumObj(day.target)}
function init(){els.daySelect.innerHTML=trip.map((d,i)=>`<option value="${i}">${formatDate(d.date)} · ${d.place}${isClosed(d)?' ✓':hasProgress(d)?' •':''}</option>`).join('');els.daySelect.value=String(currentIndex);els.daySelect.addEventListener('change',()=>{currentIndex=Number(els.daySelect.value);renderDay()});els.form.addEventListener('submit',closeDay);els.saveProgress.addEventListener('click',saveProgress);els.reopenDay.addEventListener('click',reopenDay);$('resetBtn').addEventListener('click',resetData);keys.forEach(k=>els.inputs[k].addEventListener('input',renderDaySummary));document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>showScreen(btn.dataset.go)));renderAll()}function showScreen(name){if(window.innerWidth>600)return;document.querySelectorAll('.app-screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===name));window.scrollTo({top:0,behavior:'smooth'})}function renderAll(){renderDashboard();renderDay();renderTable();refreshSelectLabels()}function refreshSelectLabels(){[...els.daySelect.options].forEach((o,i)=>{const d=trip[i];o.textContent=`${formatDate(d.date)} · ${d.place}${isClosed(d)?' ✓':hasProgress(d)?' •':''}`})}
function renderDashboard(){const totalGross=sumTrip('gross'),totalNet=sumTrip('net'),closed=trip.filter(isClosed),withProgress=trip.filter(hasProgress),actualSpent=withProgress.reduce((s,d)=>s+sumObj(actualFor(d)),0),registeredSavings=withProgress.reduce((s,d)=>s+actualSavings(d),0),projectedSpent=trip.reduce((s,d)=>s+projectedSpendFor(d),0),projectedSavings=totalNet-projectedSpent,done=closed.length,inProgress=trip.filter(d=>hasProgress(d)&&!isClosed(d)).length,usage=totalNet?projectedSpent/totalNet*100:0;$('realSavings').textContent=money(registeredSavings);$('realSavingsPerson').textContent=`${money(registeredSavings/PEOPLE)} por persona`;$('projectedSavings').textContent=money(projectedSavings);$('projectedSavingsPerson').textContent=`${money(projectedSavings/PEOPLE)} por persona`;$('actualSpent').textContent=money(actualSpent);$('daysDone').textContent=`${done} cerrados${inProgress?` · ${inProgress} en curso`:''}`;$('projectedSpent').textContent=money(projectedSpent);$('budgetUsage').textContent=`${usage.toFixed(1)}% del disponible`;$('grossBudgetLabel').textContent=money(totalGross);$('netBudgetLabel').textContent='Presupuesto total';$('netBudgetText').textContent=money(totalNet);$('progressBar').style.width=`${Math.max(0,Math.min(100,usage))}%`}
function renderDay(){const d=trip[currentIndex],actual=actualFor(d),closed=isClosed(d),progress=hasProgress(d);els.dayMeta.innerHTML=`<strong>${formatDate(d.date)} · ${d.place}</strong><br>Bruto ${money(sumObj(d.gross))} · Neto ${money(sumObj(d.net))} · Proyectado Excel ${money(sumObj(d.target))}${progress?`<br><b>${closed?'Día cerrado':'Día en curso'}</b> · Registrado ${money(sumObj(actual))}`:''}`;keys.forEach(k=>{els.inputs[k].value=progress?String(actual[k]??0):'';els.inputs[k].disabled=closed;els.inputs[k].placeholder=d.target[k].toFixed(2);els.hints[k].textContent=`Proyectado Excel: ${money(d.target[k])}`});els.saveProgress.hidden=closed;els.closeDay.hidden=closed;els.reopenDay.hidden=!closed;els.saveMessage.textContent=closed?'Día cerrado. Si necesitas corregir algo, pulsa “Reabrir día”.':progress?'Avance guardado. Puedes seguir agregando gastos cuando quieras.':'';renderDaySummary()}
function readInputs(){const out={};for(const k of keys){const v=parseFloat(els.inputs[k].value);out[k]=Number.isFinite(v)&&v>=0?v:0}return out}function renderDaySummary(){const d=trip[currentIndex],actual=readInputs(),target=sumObj(d.target),net=sumObj(d.net),act=sumObj(actual),savings=net-act;$('daySummary').innerHTML=`<div class="mini-stat"><span>Proyectado Excel</span><strong>${money(target)}</strong></div><div class="mini-stat"><span>Ingresado</span><strong>${money(act)}</strong></div><div class="mini-stat ${act<=target?'positive':'negative'}"><span>Vs. proyectado</span><strong>${act<=target?'+':''}${money(target-act)}</strong></div><div class="mini-stat ${savings>=0?'positive':'negative'}"><span>Ahorro hasta ahora</span><strong>${money(savings)}</strong><small> · ${money(savings/PEOPLE)} c/u</small></div>`}function writeDay(closed){const d=trip[currentIndex];saved[d.date]={actual:readInputs(),closed,updatedAt:new Date().toISOString()};persist();renderDashboard();renderTable();refreshSelectLabels();renderDay()}function saveProgress(){writeDay(false);els.saveMessage.textContent='Avance guardado. Puedes volver más tarde y seguir sumando gastos.'}function closeDay(e){e.preventDefault();writeDay(true);els.saveMessage.textContent='Día cerrado correctamente.'}function reopenDay(){const d=trip[currentIndex];if(!saved[d.date])return;saved[d.date].closed=false;saved[d.date].updatedAt=new Date().toISOString();persist();renderDashboard();renderTable();refreshSelectLabels();renderDay();els.saveMessage.textContent='Día reabierto. Ya puedes editar o agregar gastos.'}
function renderTable(){els.table.innerHTML=trip.map(d=>{const closed=isClosed(d),progress=hasProgress(d),actual=progress?sumObj(actualFor(d)):null,target=sumObj(d.target),savings=progress?actualSavings(d):plannedSavings(d);let status='<span class="status pending">Pendiente</span>';if(progress&&!closed)status='<span class="status progress">En curso</span>';if(closed)status=actual<=target?'<span class="status done">Cerrado</span>':'<span class="status over">Sobre proyectado</span>';return `<tr><td>${formatDate(d.date)}</td><td>${d.place}</td><td>${money(target)}</td><td>${progress?money(actual):'—'}</td><td class="${savings>=0?'money-good':'money-bad'}">${money(savings)}</td><td>${status}</td></tr>`}).join('');if(els.cards)els.cards.innerHTML=trip.map(d=>{const closed=isClosed(d),progress=hasProgress(d),actual=progress?sumObj(actualFor(d)):null,target=sumObj(d.target),savings=progress?actualSavings(d):plannedSavings(d);let status='<span class="status pending">Pendiente</span>';if(progress&&!closed)status='<span class="status progress">En curso</span>';if(closed)status=actual<=target?'<span class="status done">Cerrado</span>':'<span class="status over">Sobre proyectado</span>';const subtitle=closed?'Día cerrado':progress?'Gastos guardados, día abierto':'Aún sin gastos registrados';return `<article class="trip-card"><div class="trip-card-head"><div><strong>${formatDate(d.date)} · ${d.place}</strong><small>${subtitle}</small></div>${status}</div><div class="trip-card-stats"><div class="trip-card-stat"><span>Proyectado</span><b>${money(target)}</b></div><div class="trip-card-stat"><span>Real</span><b>${progress?money(actual):'—'}</b></div><div class="trip-card-stat"><span>${progress?'Ahorro actual':'Ahorro estimado'}</span><b class="${savings>=0?'money-good':'money-bad'}">${money(savings)}</b></div></div></article>`}).join('')}function resetData(){if(!confirm('¿Borrar todos los gastos reales guardados en este dispositivo?'))return;saved={};persist();currentIndex=0;els.daySelect.value='0';renderAll();els.saveMessage.textContent='Datos reiniciados.'}init();